version: '3.8'
services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
      
    networks:
      - my_network
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    
    env_file:
      - ./api/.env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./uploads:/usr/share/nginx/html/uploads
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
  
networks:
  my_network:
    external: true
