version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_game_db # Crée automatiquement une base de données
    volumes:
      - './data:/var/lib/mysql'
      - './database/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3306:3306' # Port par défaut pour MySQL
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=dracula
    networks:
      - my_network
    ports: 
      - '8080:8080'
  
networks:
  my_network:
    external: true
