name: Deploy to VPS

on:
  push:
    branches:
      - release  # Déclencher le déploiement uniquement sur la branche release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Utilisation de Node.js 20

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SECRET_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@173.249.8.29 '
          cd /home/mini-game &&
          git pull origin release &&
          docker compose -f docker-compose.prod.yml down &&
          docker compose -f docker-compose.prod.yml up -d --build
        '
